name: Shortcut (Clubhouse) Workflow
description: Updates and transitions the workflow state of shortcut stories
branding:
  icon: chevrons-right
  color: orange
inputs:
  clubhouseToken:
    description: auth token for clubhouse api
    required: true
  endStateId:
    description: id of the workflow state stories should be transisitioned to
    required: false
    default: 500014750
  addReleaseInfo:
    description: update story descriptions with link to github release
    required: false
    default: 'false'
outputs:
  updatedStories:
    description: An array of the story names that were updated
runs:
  using: node12
  main: dist/index.js
